[package]
name = "petstore-rs"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
rstest = "0.26.1"

[dependencies]
diesel = { version = "2.3.3", features = ["postgres"] }
serde = { version = "1.0.228", features = ["derive"] }
uuid = "1.18.1"
